# Generated by Django 2.2.1 on 2019-05-08 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('lotSize', models.IntegerField()),
                ('houseSize', models.IntegerField()),
                ('bedNum', models.IntegerField()),
                ('bathNum', models.IntegerField()),
                ('price', models.IntegerField()),
                ('desc', models.CharField(max_length=255)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phoneNumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VisitMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=999)),
                ('date', models.DateTimeField()),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.Estate')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.User')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=999)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.User')),
            ],
        ),
        migrations.AddField(
            model_name='estate',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.User'),
        ),
    ]
