# Generated by Django 2.2.1 on 2019-05-15 16:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tracker',
            unique_together={('user', 'url')},
        ),
    ]
