# Generated by Django 2.2.1 on 2019-05-09 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('lotSize', models.IntegerField()),
                ('houseSize', models.IntegerField()),
                ('bedNum', models.IntegerField()),
                ('bathNum', models.IntegerField()),
                ('price', models.IntegerField()),
                ('desc', models.CharField(max_length=999)),
                ('status', models.BooleanField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.User')),
            ],
        ),
    ]
