# Generated by Django 2.2.1 on 2019-05-16 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('lotSize', models.IntegerField()),
                ('houseSize', models.IntegerField()),
                ('bedNum', models.IntegerField()),
                ('bathNum', models.IntegerField()),
                ('price', models.IntegerField()),
                ('desc', models.CharField(max_length=999)),
                ('city', models.CharField(max_length=101)),
                ('zip', models.IntegerField()),
                ('status', models.BooleanField()),
                ('image', models.ImageField(upload_to='es_images/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
