# Generated by Django 2.2.1 on 2019-05-09 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Browse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageList', models.CharField(max_length=999)),
                ('estateId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Browse.Estate')),
            ],
        ),
    ]
