# Generated by Django 2.2.1 on 2019-05-17 16:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Browse', '0002_search'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='search_input',
            new_name='searchInput',
        ),
        migrations.AlterField(
            model_name='estate',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='search',
            unique_together={('user', 'searchInput')},
        ),
    ]
