# Generated by Django 2.2.1 on 2019-05-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Browse', '0003_auto_20190510_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagelist',
            name='imageList',
            field=models.ImageField(upload_to='estates/'),
        ),
    ]
