# Generated by Django 2.2.1 on 2019-05-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Browse', '0003_auto_20190510_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='image',
            field=models.ImageField(blank=True, upload_to='es_image/'),
        ),
    ]
