# Generated by Django 2.2.1 on 2019-05-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Browse', '0004_auto_20190513_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='image',
            field=models.ImageField(blank=True, upload_to='es_image/'),
        ),
        migrations.AlterField(
            model_name='imagelist',
            name='imageList',
            field=models.CharField(max_length=999),
        ),
    ]
