# Generated by Django 2.2.1 on 2019-05-14 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Browse', '0006_auto_20190513_1634'),
        ('Browse', '0006_auto_20190513_1751'),
    ]

    operations = [
    ]
