# Generated by Django 2.2.1 on 2019-05-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Browse', '0007_merge_20190514_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='buyerID',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estate',
            name='country',
            field=models.CharField(default='Iceland', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estate',
            name='estateType',
            field=models.CharField(default='Not a Castle', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estate',
            name='image',
            field=models.ImageField(blank=True, upload_to='es_images/'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='zipCode',
            field=models.IntegerField(),
        ),
    ]
