# Generated by Django 2.2.1 on 2019-05-14 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Browse', '0008_auto_20190514_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estate',
            name='buyerID',
        ),
        migrations.RemoveField(
            model_name='estate',
            name='country',
        ),
    ]
